### PR TITLE
ipv6

### PR DESCRIPTION
**Pull request by greezybacon**
Make sure ip addresses fields support ipv6 - varchar (64)

### CODE REVIEW

**Comment by urda** [comment]
Could this item be closed? It looks patched up.

**Comment by greezybacon** [comment]
It hasn't been merged yet

**Comment by protich** [comment]
Jared - Can you also add ipv6 validation to Validator::is_ip()?

**Comment by protich** [comment]
Looks good - but if I'm not mistaken you asked me to wait for index + a new md5 hash.

**Comment by greezybacon** [comment]
The updater-revisited branch is blocking this one. Once it's merged, the SQL patches for this will need to be moved to the new location. Then we can merge it. The canned-responses-in-a-filter request will get the new hash

**Comment by protich** [comment]
Jared - my apologies - totally forgot about it. I just submitted a pull request for the upgrader.

**Comment by greezybacon** [comment]
Dude, don't sweat the small stuff. It's not like this whole upgrader thing has been totally straight forward... I think this is ready for final review

**Comment by protich** [comment]
Reviewing - will merge it shortly.

**Pull request merged**
