### PR TITLE
Support canned response definition for email filters

### PR DESCRIPTION
**Pull request by greezybacon**
Allow an administrator to create a email filter and specify the canned response to be automatically appended to the ticket thread upon new ticket submission.

This will be useful for very common questions that are identifiable by keywords in the subject line and message body.

### CODE REVIEW

**Comment by protich** [comment]
I'll wait on a new hash on this PR + possible merge conflicts.

**Comment by greezybacon** [comment]
It has the new hash. I'll fix the merge conflict later

**Comment by greezybacon** [comment]
Ok. Merged the `develop` branch **again**.

**Pull request merged**
