### PR TITLE
Fixing the 'Fetch Email' features

### PR DESCRIPTION
**Pull request by ghost**
I have corrected errors related to the 'Fetch Email' feature of the application, as this feature is currently broken due to typos.

### CODE REVIEW

**Comment by ghost** [comment]
Just realized I made these commits on the master branch.  Let me know if they need to be made on the develop branch.

**Comment by greezybacon** [comment]
Thanks, putneyj, these look pretty good. Could you debase them to the develop branch?

**Comment by protich** [comment]
Thank you for the PR. Yes - you'll need to redo the PR and make sure it's to develop branch.

We hadn't started testing email fetching yet.

**Comment by protich** [comment]
See PR  #83

**Comment by adeshsuryan** [comment]
Hi,
       After setting of POP3 , system is not responding properly for fetch email functionality . Some time create Ticket properly some time not , in 10 min 6 mail are convert in form of ticket . 

Current version : 1.7 x

**Pull request closed without merging**
