### PR TITLE
Ticket Print Options

### PR DESCRIPTION
**Pull request by protich**
Staff can now print a ticket thread with or without internal notes + select paper size on the fly

### CODE REVIEW

**Comment by greezybacon** [comment]
Looks like there's a UTF-8 issue with the PDF printing -- such as international names. It's not related to these commits. If I can't find it in a few minutes, I'll post a separate issue

**Comment by protich** [comment]
Good point - I'll vote on a separate issue.

**Comment by greezybacon** [comment]
Note to self | selves, the print form will need CSRF protection

**Comment by greezybacon** [comment]
I made a couple of style tweaks. Mainly to separate the [Print] and [Cancel] buttons, and to make the dialog feel more like a common software dialog. Lemme know what you think. Otherwise, it looks ready to pull.

**Comment by protich** [comment]
Changes merged.

**Pull request merged**
