### PR TITLE
CSS Enhancements

### PR DESCRIPTION
**Pull request by soif**
Fixes
- I've (auto) reformatted the CSS.
- Changed your comments, to CSSEdit friendly group comments
- Re groupped some styles
- Removed duplicates declarations

Features Added
- Started to improve the SCP look mainly
- Started to improve the Login window

If  you like, i can finish it (fix some table widths in the client view, and some margins)

Comments, like/dislike welcome!

### CODE REVIEW

**Comment by protich** [comment]
What's the purpose of .wrapper  and where is it defined?

**Comment by soif** [comment]
the .wrapper is defined in scp.css. 
It is used to define the width of all page elements while allowing each individual divs #ids to get their own width. I used this to have the #header full-width, while keeping the others page element use the .wrapper width. It could also be used, the same way, to get a full width footer.

On the other hand, the #wrapper class (unused at this time), allows to a have simple css overriding rules like
#wrapper{width 960px}
.wrapper{width: 100%}
to revert back to something nearest your previous layout.

While we are on CSS, i would like (if you like me helping to clean the CSS and make it more universal to anyone wanting to easily override the default CSS, to its own design) to add  a unique css id to the BODY tag.

something like &lt;BODY id="page_{$page}" &gt;
 ie &lt;BODY id="page_emailtest" &gt;

This tag only would allow any page to get its own rules easely overrided, without changing a sinle line of code. ie
#page_emailtest TABLE {margin-top:50px}

**Comment by soif** [comment]
oups , my git client software seems to have committed a lot of unwanted commits to this branch.. I'm gonna clean this...

**Comment by soif** [comment]
Commits cleaned.

**Comment by soif** [comment]
Should I continue to improve the css, and to move hard-coded styles into the stylesheets?
Do you like the look? Not? Some directions?

**Comment by soif** [comment]
I almost finished to improve and clean the Client Pages: 
- slightly improved  pages looks
- cleaned the CSS file, removed all un-needed declarations and regrouped declarations
- removed all hard coded CSS styles
- cleaned the HTML

I've some ideas for the FAQ sections (coming soon)

If you like, I will soon finish and test/fix with all web browsers, especially IE (not tested at this time).

**Comment by soif** [comment]
Any thought ?

**Comment by soif** [comment]
Would you please tell me if I continue or not?
Doing this has already required a lot of time: I don't want to spend any more hours in this direction, if you just don't like it?

**Comment by protich** [comment]
I'll get someone to review the pull request.

**Comment by soif** [comment]
thank you, very much!

Notes for the (future)  reviewer: 
Currently:
- Client pages are enhanced, except the FAQ pages (coming very very soon, if you'd post some positive feedback)
- SCP has got some cleaning, and minor enhancements only.

Some issues should still exist on Internet Explorer, but it should be almost finished on Webkit (Chrome, Safari) and Mozilla.

So please first review it first with Google Chrome or Safari !

**Comment by soif** [comment]
hum? :-)

**Comment by soif** [comment]
I've just re-cleaned all commits to be merge-able into current develop (rc2) branch...

**Comment by kellishaver** [comment]
I've taken a look over the CSS edits. These changes are largely irrelavent. 

Indentation is a non-issue for anyone, as it's completley configurable in any decent code editor.

Wrapper serves no purpose. It duplicates the functionality of #container.

As for the duplicate entries, this is because of the way the CSS is complied by LESS.

Regarding "improvements" to the look of osTicket - We have spent a great deal of time working out the visual style and feel like it's pretty solid. Right now we're more concerned with browser compatibility fixes. 

I'm getting ready to review the CSS as part of a round of already-planned revisions to the interface.

A better option would probably be for me to add the original LESS files to the repository after that's done and then any bug fixes relating to browser compatibility can be done on those and then recompiled to CSS. 

I feel like the css files should be the minified versions, anyway, and then all editing and changes handled in the LESS files after the next round of revisions. This will also make it much easier for people to customize their individual osTicket installation, since it will give us better separation and better formatting.

**Comment by soif** [comment]
1) Indentation: I never intended to propose the indentation as a "feature". It's just because my CSS editor allow me to clean it fastly (having one style per line), that I've re-indended the whole stylesheet to make it more readable for a human, ie the reviewer or the OST user... 

2) Wrapper:
I started on the idea that every OST user might like to easily customize OST CSS to match their own web site design.

Wrapper does not duplicate the functionality of #container. It allows to easily have a full-width footer and header (like half of websites have nowadays, ie github...). I used this in the scp.

Does the #container allow that, without hacking the code? NO!
It can certainly be improved, but the current implementation is absolutely not flexible, for anyone wanting to display OST in his own website.

3) duplicate entries: 
I can't guess that you generate CSS from a specific process ("LESS"), as no sources are currently provided. So I just cleaned the duplicate lines, to make the code more readable. You wont blame me for this, would you?

4) Improvements: 
As you might have seen, I tried to NOT radically change the look of OST, I just added a very little taste of modernness (this is obviously a matter of taste) , while trying to start to have re-usable css classes, and removing all hard-coded styles (which is absolutely ugly for any designer, and also non w3c compliant). I think "my design" does not really change the current OST look, but allow anyone to adapt it to its own needs , without having to hack the whole php code.

5) LESS, minify and user ease-of-use. 
While having designed hundred of websites (including some Google PR 5 ones), I was not aware of LESS, and I'm happy to have learned something interesting today. But do you think the average OST user will use LESS, or make their own stylesheet, the usual way? 
Shoud'nt we then provide them a clean, human readable CSS, or a complicated CSS+JS solution (as LESS is).

For the same reason, and because a Ticket system is not intended to rank on the fastest google sites results, should we provide an un-readable minified CSS, instead of a clean, easily human-hackable CSS, when minifying it is just a matter of a 3 sec. copy/paste, when the user really care about it.

**Comment by kellishaver** [comment]
>  that I've re-indended the whole stylesheet to make it more readable for a human

My point is that you don't need to do this. "Human readable" is highly subjective, hence the reason you set your preferred format in your editor's preferences and go with that. You don't just come in to a project and completely ignore/change whatever style that may already be in use. It's very poor form. I refuse to discuss this further. It's a waste of time.

> I started on the idea that every OST user might like to easily customize OST CSS to match their own web site design.

Anyone who wants the level of customization and integration with their existing layout that you're suggesting is going to need to modify the markup as well as the CSS. If they need to add a wrapper, they can add it then. It serves no purpose in the default theme. In the future, themes and templates will be implemented to make customization easier for the 'average person." In the mean time, changing the look is not possible without some basic HTML/CSS knowledge to begin with, so, again, this is a non-issue.

>  can't guess that you generate CSS from a specific process ("LESS"), as no sources are currently provided. So I just cleaned the duplicate lines, to make the code more readable. > You wont blame me for this, would you?

No, not at all, sorry if it sounded like I was. If anyone is at fault on that it's me, for not providing them in the first place. Much of my work on 1.7 was done while I was dealing with some pretty serious medical issues that obviously took priority and I'm just now getting back into the project. So I will be doing a lot of clean-up including packing the LESS files in the repo after we've gone through a round of UI revisions that Peter has planned.

I wasn't so much saying that cleaning up the duplication, etc. was wrong or a bad thing to do. It's certainly not. What I meant was that these issues will be handled in the LESS files, so right now any changes to the CSS should focus on browser compatibility, so we can reference them to 'patch' the LESS files when we do the revisions.

Until the LESS files are available in the repo, making syntactical or cosmetic changes isn't something we're going to accept. After the LESS files are included, any changes should be made to them and then the CSS recompiled. That's all I meant. 

> 4) Improvements: 

I agree, in-line styles should be removed, if they exist. I need to re-familiarize myself with the code. 

> While having designed hundred of websites (including some Google PR 5 ones), I was not aware of LESS, and I'm happy to have learned something interesting today. But do you think the average OST user will use LESS, or make their own stylesheet, the usual way?

I find it odd that Google PR is the metric by which you judge your success as a developer.... Anyway, at this point, until such time as themes and templates are implemented, the "average" person customizing osTicket is either going to know how to do it or they're going to hire someone who does. That said, you do make a good point.

> Shoud'nt we then provide them a clean, human readable CSS, or a complicated CSS+JS solution (as LESS is).

Shouldn't... Two things here:
1. I agree, a providing non-minified CSS file is fine, and a good idea, because someone out there will want to deviate from the norm and will not want to use LESS to do so, but I still think providing, and using by default, a minified one is better. So really, we should be doing both, while also encouraging the LESS adaptation for the sake of future compatibility.
2. This is more of an FYI should you want to look into it more, but LESS is not a complicated JavaScript solution. If you're using LESS JavaScript in your production code, you're doing things _very_ wrong. The JavaScript complication is meant for testing and development. You should only ever be linking to complied versions of your CSS in your production code. LESS files should never be compiled at run-time outside of a test/dev environment.

**Comment by soif** [comment]
(Following this issue and #227, #197 ... etc...)

OK. Let's stop this now.

All you've already done (you and peter)  is either not-enhanceable (because it is just perfect) or is already planned in a future that no-one (expect you) is aware. :-/

I've perfectly understood that every effort to contribute in any way to OST, is a waste of time, because everything I'd propose is  immediately "largely irrelevant", a "non-issue", "serves no purpose",  "is a waste of time", or  I "seriously don't see the problem", I "just being disagreeable for the sake of it" etc.... :-O

Thank you to have been kind enough to spend some time to teach an idiot like me: 
I swear I won't waste your time (and mine) anymore.

BTW good luck to motivate the next contributors.... ;-)

**Comment by protich** [comment]
@soif - I personally would rather have no feature than poorly implemented feature. You've got to be able to backup your claims and explain your implementation decisions and assumptions.

You're not an idiot (your attention to details is impressive) but you've got to work on accepting that we can all be wrong sometimes - don't take challenges to your work/logic personally. You're new to osTicket - you can't expect to be an expert on why things are implemented as it is...etc ( See @greezybacon response on #195). 

Both issues #197 & #227 illustrates my point - you either made stuff up (strong word - but examples are on comments)  or simply ignored counterpoints - making it impossible to work with you in getting to the core of the issue, from our point of view.

Best of luck.

**Comment by drewx0r** [comment]
You guys have a great product. I like it a lot. It's simple, elegant, and gets a lot of things right. Also, it's open source, which is wonderful. But please don't fall victim to that open source pitfall of being dismissive of people who are trying to help. It happens all the time. It'd be a shame for it to happen here.

I don't think soif taking his ball (and one's ideas, and one's obvious fixes) and going home is the right way to respond this. Sadly, I can understand the frustration, as, far from being a outlier, this type of dismissive response is really really prevalent in open source projects. 

It's par for the course for someone with an "official" role in an OSS project to get superdefensive about code. It makes sense, in a way; code can be very personal and any suggestion to change it in a way you hadn't considered or don't agree with can become viewed as an attack on you personally. This is a ridiculous way to look at things, but it happens. Look above; it just did.

I was going to take kellishaver to task for the dismissive tone taken, including the completely unnecessary spelling correction (which I suppose was intended to discount the larger argument?) I thought about going through and documenting kelli's spelling errors (there are a few) just to show how silly and petty such things are, but I think we're all adults here (I hope) and already know just how silly this whole exchange got.

soif's suggestions have some merit, and if they don't mesh with the way in which the maintainers of this project are designing and improving this project, that needs to be explained politely and respectfully. soif isn't trying to destroy your code or your project. soif is not offering suggestions because he thinks your project sucks. Soif is offering suggestions because he (he?) _likes_ your project, wants it to thrive, and has some ideas that he thinks should help. Being curt and dismissive is not going to do the project any good. 

I hope this doesn't become the normal way of responding to people with suggestions. I have suggestions from time to time, some of which I've implemented on my own, but none of which I've yet brought to the github as a pull. This sort of tone of discussion doesn't make me enthusiastic to do what little I can to help the project.

Anyway, keep up the good work on the project. I can't wait for the last bugs to be ironed out of 1.7, as it contains a couple of really great enhancements and I can't wait to deploy it. I hope it's clear that I'm rooting for this project wholeheartedly and I'm only writing this diatribe because I want it to be successful.

Cheers,

Andrew

**Comment by protich** [comment]
@drewx0r I appreciate your comment and suggestions. osTicket is **simple & elegant** (your words) AND we'll like to keep it that way. We challenge every implementation (including mine) to make sure assumptions are flushed out and the **real** core issue is addressed. Accepting every pull request will be detrimental to what osTicket is about - and I hope you'll also agree that it's a pitfall that often befalls many open source projects.

@soif has made great suggestions and we've accepted some of his pull requests, more than anyone outside the core developers.

**Comment by drewx0r** [comment]
Definitely true. One would think that a project like SeaMonkey has a quota of pull requests they have to accept each week, to their great detriment.

My issue wasn't with the result, but with the tone. It's possible to reject a pull request and have the person who was rejected understand and feel comfortable with the rejection because the reasoning behind it was laid out dispassionately and logically, and with a modicum of respect. 

Anyway, I'll probably be starting a new thread to deal with another pull request that soif closed out. I won't open it as a pull request, but as a bug report, which I think you find less controversial. It's a file naming issue that causes the knowledgebase entry php to fail. I'll just link to it here. It's issue #229

**Comment by protich** [comment]
@drewx0r - I ask that you also see it from the point of view of OSS maintainer - it's not customer support type interaction especially when the contributor ignores the counterpoints or simply refuse to take advice (see #195, #197, #227).  Being blunt help drives home the point (sometimes), otherwise it becomes a time wasting cycle.

That said, I'll check my frustration meter going forward (at least before I hit submit) but contributors should expect to be challenged and sometimes rejected.

Cheers

**Comment by soif** [comment]
@drewx0r thank you for your understanding. 

You've written 100% of what I feel, for the rest see #195

**Pull request closed without merging**
