### PR TITLE
Dynamic data for osTicket

### PR DESCRIPTION
**Pull request by greezybacon**
_This is a major redesign / rework of the osTicket base_

This patch drops the concept of static ticket metadata and allows for an admin-configurable arbitrary data that is attachable to tickets

The system is architected such that the base osTicket install now comes with a "default" form that has fields for subject, name, email, and phone number. This form is editable to allow for the addition of arbitrary other fields; however, the basic fields must remain in order to be associated with a help-topic and attached to a ticket.

This concept can be expanded to allow for arbitrary data associated with registered clients or ticket thread items.

Forms are comprised of sections. Sections have a title and instructions properties and a list of fields. Fields have various implementations to represent different data such as text, long answer, phone number, datetime, yes/no, and selections, and are configurable to define the look and feel and interpretation of the respective form field.

Dropdown lists are represented as "Dynamic Lists", which are admin-configurable lists of items. Dropdowns can be optionally represented as Bootstrap typeahead fields.

This also adds the start of a simple ORM which will hopefully be expanded in the future to support multiple database platforms. Currently, only MySQL is implemented.

**WARNING** _Experimental code_: For now, this patch only supports clean installations. A start of an upgrade script is included, but is neither integrated with the upgrade system nor tested.

I would like to see early adopters and aggressive testers help in debugging the last of issues and sniff out the remaining requirements.

Known Outstanding Issues (last mile):
- Delete support for big dynamic items (list, section, form)
- Email integration -- allow submission without required fields not represented in MIME
- Upgrade testing
- PDF layout fixes
- Icons for the admin interface menu for dynamic forms
- Documentation
- Private data may leak on email from email templates

Extra features TODO:
- Custom regex validator for the text field

### CODE REVIEW

**Comment by mrmj2u** [comment]
Hey buddy, I'd like to help to test this for you. Please let me know how to get the files downloaded for our test site.

**Comment by greezybacon** [comment]
You can get the source from the repo at https://github.com/greezybacon/osTicket-1.7/tree/feature/dynamic-forms. You can also use the [Download ZIP] button on the right to download a zip-ball of the repo.

Hope this helps

**Comment by mrmj2u** [comment]
Thanks, I've got it up and running now. Just need to get a few DB errors under control.

DB Error #1054 - Unknown column 'phone' in 'field list' 

Shows up when viewing tickets in the staff panel.

**Comment by krzysiek988** [comment]
Great mod! I've downloaded and istalled it and it's working wonderful! But I have one problem with it. When I create some test tickets as a client and I want to check status of those created tickets (I'm using email adress and ticket #) I can't do this, because it's showing me an error: "Authentication error - try again!". How can I fix it? It's a fresh install without any other modifications.

**Comment by greezybacon** [comment]
@krzysiek988, this pull is suffering some bitrot. We're going to release osTicket 1.7.1 within a week, and thereafter, we're going to fixup and merge this guy. I would suggest, if you could, evaluate all that is working and please continue to comment. Hopefully this will be merged into the mainline `develop` branch within a month

**Comment by krzysiek988** [comment]
As I was translating osTicket I didn't find enough time to check if everything works fine. I found some other problems, like when I allowed adding attachments it became possible only for staff tickets. From client side there is no possibility to add anything to ticket. Printing tickets works fine. I have a small problem with characters encoding, cause I'm translating osTicket into polish and I get some weird marks instead of normal characters. I tried changing encoding to iso8859-2 but it didn't work. I also tried to add some polish fonts and change database collation, but it also didn't work. So I have to find another way to fix it. I assume that there is a problem with fpdf library. Beside those two problems I find this modification working great so far. If I come up against anything I'll let you know.

**Comment by krzysiek988** [comment]
I've downloaded and installed 1.7.1 version, but after applying dynamic data mod I'm still experiencing problems with client login. I can't check ticket status, because every time I try to do this I get message: "Authentication error - try again!". And I'm sure, that ticket ID and email adress are correct. I tried this with 1.7.1 version without any mods applied and it worked without any problem. Could you please give me a hint where should I look to fix this?

**Comment by greezybacon** [comment]
@krzysiek988, the login bug is in `class.ticket.php`, line 1663:

``` php
    .' WHERE field.name = "email" AND ticeket.ticketID='.db_input($extId);
```

should be

``` php
    .' WHERE field.name = "email" AND ticket.ticketID='.db_input($extId);
```

I'm officially deprecating this pull request. We've decided to fork to osTicket-1.8 and merge it there. I've freshened the code up and am actively developing it there.

1.8 will also have official support for internationalization, so I would prefer for you to spend your time working with the new codebase. Beware, though, we're working on mocking up the major features for 1.8, including dynamic forms, so the code is still changing very significantly.

That said, we are very interested in getting help to cleanup the code to make it more translatable (remove concatenated strings, clean up inconsistencies in message, etc.).

I really appreciate your help thus far!

**Comment by krzysiek988** [comment]
One wrong letter... why wouldn't I think about that? It solved authentication problem. I also found temporary solution to Database Error #1054. The fastest way is to just add columns 'phone' and 'phone_ext' to ost_ticket table using following SQL queries:

ALTER TABLE `database_name`.`ost_ticket` ADD COLUMN `phone` VARCHAR(16) AFTER `updated`

and

ALTER TABLE `database_name`.`ost_ticket` ADD COLUMN `phone_ext` VARCHAR(8) AFTER `updated`

Of course those fields will duplicate but only place, where I found them is in a client's created ticket view. I just removed this field from ../include/client/view.inc.php
If I find it anywhere else I'll post it here. But for now those modifications didn't cause any major problems. And my logs are clear so far.

**Comment by greezybacon** [comment]
@krzysiek988, thanks again. To fix the phone bit properly, use this in `class.client.php` in the `load` method:

``` php
    function load($id=0, $email=null) {

        if(!$id && !($id=$this->getId()))
            return false;

        $sql='SELECT ticket.ticket_id, ticketID, email.value as email, phone.value as phone '
            .' FROM '.TICKET_TABLE.' ticket '
            .' LEFT JOIN '.DYNAMIC_FORM_ENTRY_TABLE.' entry ON entry.ticket_id = ticket.ticket_id '
            .' LEFT JOIN '.DYNAMIC_FORM_ANSWER_TABLE.' email ON email.entry_id = entry.id '
            .' LEFT JOIN '.DYNAMIC_FORM_FIELD_TABLE.' field1 ON email.field_id = field1.id '
            .' LEFT JOIN '.DYNAMIC_FORM_ANSWER_TABLE.' phone ON email.entry_id = entry.id '
            .' LEFT JOIN '.DYNAMIC_FORM_FIELD_TABLE.' field2 ON phone.field_id = field2.id '
            .' WHERE field1.name = "email" AND field2.name="phone" AND ticketID='.db_input($id);

        if($email)
            $sql.=' AND email.value = '.db_input($email);
```

Please continue the discussion in the osTicket-1.8 repo [https://github.com/osTicket/osTicket-1.8/pull/2](here). That's where I plan to merge the branch. I've also already fixed the phone-number issue there. Furthermore, we aim to make 1.8 fully translatable and will very likely accept translation pull-requests for the project. There is an issue currently open to try and get the internationalization efforts organized.

**Comment by krzysiek988** [comment]
I've got one more question, because in this modification there is a huge problem with autoresponder function. When I create a new ticket, I don't get any message on my mailbox. When I add any answer to a ticket or assign anyone, I get a messege from autoresponder. I didn't enter any settings and system sends notifications after something is going on with a ticket but no messages after creating new ticket. Of course I configured this option in system preferences, but it's still not working. I tried to check this with few different email adresses and tried configuring smtp, but none of those solutions seemed to work. Do you have any idea for this?

**Comment by greezybacon** [comment]
I was able to reproduce this today on the 1.8 branch. I'll get back to you with the fix

**Pull request closed without merging**
