### PR TITLE
Included LDAP Config

### PR DESCRIPTION
**Pull request by jdelhome3578**

### CODE REVIEW

**Comment by greezybacon** [comment]
This will be implemented in osTicket-1.8 along with pluggable authentication which will allow for authentications other than built-in and LDAP

**Comment by Richiricheh** [comment]
Is the plan to also allow SSO using LDAP in 1.8?

Kind regards,

Rich Cocksedge
Manager, Information Technology
Phone: 416 231 7680 Ext.3122
email: rcocksed@united-church.camailto:rcocksed@united-church.ca

**Comment by greezybacon** [comment]
@Richiricheh, I'm not familiar with SSO implemented with LDAP. Are you talking about Kerberos?

**Comment by jdelhome3578** [comment]
here is the mod
http://www.osticket.com/forums/forum/osticket-1-7-latest-release/mods-and-customizations-aa/9246-mod-ldap-authentication

**Comment by Richiricheh** [comment]
It is possible to use basic LDAP for SSO but it is not nearly as secure as using Kerbos. I have a mod built on older 1.7 code using KERBOS + LDAP for SSO. I took the code a step further and made it so that a list of the authenticated users tickets were displayed on the main page. I was asking if SSO was already in place (KERBOs or not) so I could determine if I should spend, please read as not waist, more time maintaining this code.

Kind regards,

Rich Cocksedge
Manager, Information Technology

**Pull request closed without merging**
