### PR TITLE
Fixup old ..MsgTemplate() getters which returned arrays

### PR DESCRIPTION
**Pull request by greezybacon**
This further fixes #610

### CODE REVIEW

**Comment by josh1856** [comment]
I pulled this and am still able to replicate the error.

########## START #########
Warning: preg_match_all() expects parameter 2 to be string, object given in /home/support.xyz.com/htdocs/include/class.variable.php on line 124

Fatal error: Cannot use object of type EmailTemplate as array in /home/support.xyz.com/htdocs/include/class.ticket.php on line 747
#########END###########

**Comment by josh1856** [comment]
I was able to resolve the issue and create the ticket properly but it is still not properly being displayed in the confirmation page.

ticket_response

**Comment by greezybacon** [comment]
@josh1856, I didn't merge the fix into the develop branch. Did you try it on the greezybacon:issue/610 branch or the develop?

**Comment by josh1856** [comment]
greezy: I pulled the development branch and then made the changes manually.

**Comment by greezybacon** [comment]
> I was able to resolve the issue and create the ticket properly but it is still not properly being displayed in the confirmation page

@josh1856, it seems to work correctly in my tests. What do you mean when you say it's not displayed properly? Are you referring to the X's?

**Pull request merged**
