### PR TITLE
Fix Faq list include error

### PR DESCRIPTION
**Pull request by soif**
Missing faq-category.inc in faq list view.

### CODE REVIEW

**Comment by drewx0r** [comment]
Knowledgebase articles won't load for users if the filename isn't changed.

**Comment by soif** [comment]
Sorry, I don't understand what you're meaning.

**Comment by drewx0r** [comment]
Sorry I wasn't clear enough. I'm just agreeing with you. the kbase throws an error unless, as you said, kb-category.inc.php gets changed to faq-category.inc.php.

Cheers.

**Comment by soif** [comment]
#172

**Pull request closed without merging**
