### PR TITLE
Faster SQL-query

### PR DESCRIPTION
**Pull request by eivindgit**
Faster SQL-query, huge performance improvement on installations with thousands of tickets. We use osTicket and have about 25 000 tickets and it was getting slow.

### CODE REVIEW

**Comment by greezybacon** [comment]
This looks good. Thanks for taking the time to propose it

**Comment by eivindgit** [comment]
Thank you for bringing life into osTicket again! We were looking into changing system before the development startet up again!

**Comment by greezybacon** [comment]
Absolutely no offense, @eivindgit, I confirm that your query runs about ~380ms less (~390ms down to ~10ms) on a system with about 9k tickets, or about 40x faster. This is huge. Thanks so much.

Where clauses with '1 OR ...' or '1=1 OR ...' give me hives and just look like SQL injection. Also, your proposal might use `$where2` uninitialized. Instead of bugging you about it, I pulled your commit, made the changes and proposed #862.

**Comment by eivindgit** [comment]
You are totally right @greezybacon, thanks for the code review!

**Pull request closed without merging**
