### PR TITLE
Format root files for consistency

### PR DESCRIPTION
**Pull request by BafS**
I have format files from root because there is a lot of inconsistency in the code. There is still a lot to clean ;)

### CODE REVIEW

**Comment by protich** [comment]
@BafS - Are you doing it manually or via a shell script? I'll vote for cleaning up the entire code base - now that v1.7.0 is out of the way. :+1:

**Comment by BafS** [comment]
Some regexes, a bit manually and also with the eclipse formatter.
I think the code is near the 1TBS style (http://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS).
We can also follow the PSR-0, PSR-1 and PSR-2 (for style) but it would be a big re-factoring. You want it to be compatible with with PHP5+ ? (5.3+ is-it OK ?).

**Comment by protich** [comment]
I'll say consistent 1TBS will do - not a big fan of some aspects of PSR. We'll work on putting together a rough doc on expected coding style going forward - I'll ping you for feedback once we have a draft.

That said, version 1.7 series supports PHP 4.4+ so PHP5 compatible styling is a no go for now. But... starting with 1.8 series, we'll require PHP 5.3+ and will include major overhaul - e.g  templating engine and ORM.

**Comment by BafS** [comment]
Okay nice. Templating and ORM are a really good idea (and why not a MVC structure ?).

**Comment by protich** [comment]
I'm open to MVC - templating engine will get us halfway there by separating presentation from the logic.

**Comment by BafS** [comment]
Yep, a promising future.

**Comment by greezybacon** [comment]
I'd like to add that 1.7 presents a URL dispatcher for the API and AJAX callbacks, so we have the _C_ part of the MVC already. So technically, ORM and template engine should get us all the way there

**Pull request closed without merging**
